export const TOGGLE_ADD_WORKOUT = "TOGGLE_ADD_WORKOUT";
export const TOGGLE_EDIT_WORKOUT = "TOGGLE_EDIT_WORKOUT";
export const UPDATE_SELECTED_WORKOUT = "UPDATE_SELECTED_WORKOUT";
export const UPDATE_SELECTED_DAY = "UPDATE_SELECTED_DAY";